
export const GET_BOOKS_REQUEST="GET_BOOKS_REQUEST";
export const GET_BOOKS_SUCCESS="GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAILURE="GET_BOOKS_FAILURE"

export const PATCH_BOOK_REQUEST="PATCH_BOOK_REQUEST";
export const PATCH_BOOK_SUCCESS="PATCH_BOOK_SUCCESS";
export const PATCH_BOOK_FAILURE="PATCH_BOOK_FAILURE"